---
title: "Tarea sección 7 Estructura de datos con R"
author: "Sección 5"
date: "23/4/2020"
output:
  pdf_document: default
  html_document: default
---
## Tarea Sección 7

1- Cread un vector llamado "Harry" formado por la sucesión de números consecutivos entre el -10 y 27. Pedidle a R que os devuelva el elemento de índice 7. Escribid el resultado.

Harry = -10:27

Harry[7]

2- Dad el máximo de la sucesión (100*2^n -7*3^n) con n=0,...,200

n = 200

maximo = (100*2^n)-(7*3^n)

maximo

3- Cread la sucesión de números consecutivos entre 0 y 40. A continuación, cread el vector (3*5^n - 1) con n=0,...,40. Ponedle como nombre x. Ahora, dad el subvector de los elementos que son estrictamente mayores que 3.5

n = 0:40

vector= 3*5^(n-1)

subvector1 = vector>3.5 ## Resultado en logico

subvector1

subvector2 = vector[vector>3.5] ## Resultado en numeros

subvector2

4- Cread una función que os devuelva la parte real, la imaginaria, el módulo, el argumento y el conjugado de un número, mostrando solo 2 cifras significativas

RECOMENDACIÓN: En algún momento os hará falta utilizar vectores

No conseguí entender esta pregunta por eso lo la hice.

5- Cread una función que resuelva ecuaciones de segundo grado (de la forma Ax^2+Bx+C=0). No importa, por ahora, que tengáis en cuenta las que no tienen solución

RECOMENDACIÓN: En algún momento os hará falta utilizar vectores

e2gpositivo= function(a,b,c){(-b +sqrt((b^2)-(4*a*c)))/(2*a)}

e2gnegativo= function(a,b,c){(-b -sqrt((b^2)-(4*a*c)))/(2*a)}

e2gpositivo(1,8,3)

e2gnegativo(1,8,3)

6- Tomando el vector vec = c(0,9,98,2,6,7,5,19,88,20,16,0), dad 3 opciones diferentes para calcular el subvector c(9,19,20,16)

Tomando el vector vec definido en el apartado anterior, buscad

    - qué entradas son pares

    - qué entradas no son pares y mayores que 20

    - dónde toma vec su valor máximo

    - dónde toma vec sus valores mínimos

vec = c(0,9,98,2,6,7,5,19,88,20,16,0)

vectordenado= sort(vec)


Subvector1 = vec[which(vec<88 & vec>8)]

Subvector1

Subvector2 = vec[vec < 88 & vec > 8]

Subvector2

Subvector3 = vectordenado[7:10]

Subvector3


Pares = vec[vec%%2 ==0] ## Da los resultados de las entradas pares

Pares

Impar = vec[vec%%1 ==0] ## Salida todos los vectores impares

Impar

Imparmayor20 = Impar[Impar>20] ## Salida los vectores impares > 20

Imparmayor20

Max = vec[which.max(vec)] ## Salida el vector maximo

Max

Min = vec[which.min(vec)] ## Salida el vector minimo

Min

7- Adjunta las instrucciones para resolver el Ejercicio 1 del PDF adjunto

8- Adjunta las instrucciones para resolver el Ejercicio 2 del PDF adjunto

9- Adjunta las instrucciones para resolver el Ejercicio 3 del PDF adjunto

10- Adjunta las instrucciones para resolver el Ejercicio 4 del PDF adjunto

```{r Ejercicios de la sección 5}

A = rbind(c(1,3),c(2,4))
R1a = A%*%(A+A)%*%A

B = rbind(c(2,4,-6),c(0,0,3), c(0,-2,5))
Vapb = eigen(B)$values ## Valor propio de B

C = rbind(c(-48,35,-12),c(-134,95,-32), c(-194,33,-44))
Vepc = eigen(C)$vectors ## Vector propio de C con 3 decimales
round(Vepc, 3)

D= rbind(c(-2,-8,-2,3), c(-3,-6,-1,2),c(-9,-22,-3,7),c(-18,-44,-8,15))
Rd= qr(D)$rank ## Rango de la matriz D

## Cread un vector llamado "Harry" formado por la sucesión de números consecutivos entre el -10 y 27. Pedidle a R que os devuelva el elemento de índice 7. Escribid el resultado.

Harry = -10:27
Harry[7]

## Dad el máximo de la sucesión (100*2^n -7*3^n) con n=0,...,200
n = 200
maximo = (100*2^n)-(7*3^n)
maximo

## Cread la sucesión de números consecutivos entre 0 y 40. A continuación, cread el vector (3*5^n - 1) con n=0,...,40. Ponedle como nombre x. Ahora, dad el subvector de los elementos que son estrictamente mayores que 3.5

n = 0:40
vector= 3*5^(n-1)
subvector = vector>3.5 ## Resultado en logico
subvector = vector[vector>3.5] ## Resultado en numeros

## Cread una función que os devuelva la parte real, la imaginaria, el módulo, el argumento y el conjugado de un número, mostrando solo 2 cifras significativas RECOMENDACIÓN: En algún momento os hará falta utilizar vectores

## Cread una función que resuelva ecuaciones de segundo grado (de la forma Ax^2+Bx+C=0). No importa, por ahora, que tengáis en cuenta las que no tienen solución

e2gpositivo= function(a,b,c){(-b +sqrt((b^2)-(4*a*c)))/(2*a)}
e2gnegativo= function(a,b,c){(-b -sqrt((b^2)-(4*a*c)))/(2*a)}
e2gpositivo(1,8,3)
e2gnegativo(1,8,3)

## Tomando el vector vec = c(0,9,98,2,6,7,5,19,88,20,16,0), dad 3 opciones diferentes para calcular el subvector c(9,19,20,16)
##Tomando el vector vec definido en el apartado anterior, buscad
## qué entradas son pares
## qué entradas no son pares y mayores que 20
## dónde toma vec su valor máximo
## dónde toma vec sus valores mínimos

vec = c(0,9,98,2,6,7,5,19,88,20,16,0)
vectordenado= sort(vec)

Subvector1 = vec[which(vec<88 & vec>8)]
Subvector1
Subvector2 = vec[vec < 88 & vec > 8]
Subvector2
Subvector3 = vectordenado[7:10]
Subvector3

Pares = vec[vec%%2 ==0] ## Da los resultados de las entradas pares
Pares
Impar = vec[vec%%1 ==0] ## Salida todos los vectores impares
Impar
Imparmayor20 = Impar[Impar>20] ## Salida los vectores impares > 20
Imparmayor20
Max = vec[which.max(vec)] ## Salida el vector maximo
Max
Min = vec[which.min(vec)] ## Salida el vector minimo
Min


```
































  